wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699470029.45584
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 19
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
